routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\UserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\CastController;
use App\Http\Controllers\FilmController;
use App\Http\Controllers\ReviewController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('film/{id}/review', [FilmController::class,'review']);
Route::get('film/tampil', [FilmController::class,'tampil']);

Route::group(['middleware' => 'auth'], function () {
    //Route User
    Route::resource('user',UserController::class,['except' => ['index', 'show']]);

    //Route Profile
    Route::resource('profile',ProfileController::class,['except' => ['index', 'show']]);

    //Route Genre
    Route::resource('genre',GenreController::class,['except' => ['index', 'show']]);

    //Route Cast
    Route::resource('cast',CastController::class,['except' => ['index', 'show']]);

    //Route Film
    Route::resource('film',FilmController::class,['except' => ['index', 'show']]);

    //Route Review
    Route::resource('review',ReviewController::class, ['except' => ['index', 'show']]);
});

//Route User
Route::resource('user',UserController::class, ['only' => ['index', 'show']]);

//Route Profile
Route::resource('profile',ProfileController::class, ['only' => ['index', 'show']]);

//Route Genre
Route::resource('genre',GenreController::class, ['only' => ['index', 'show']]);

//Route Cast
Route::resource('cast',CastController::class, ['only' => ['index', 'show']]);

//Route Film
Route::resource('film',FilmController::class, ['only' => ['index', 'show']]);

//Route Review
Route::resource('review',ReviewController::class, ['only' => ['index', 'show']]);

app/Models/Film.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Film extends Model
{
    use HasFactory;

    protected $table = "film";
    protected $fillable = ["judul","ringkasan","tahun","poster","genre_id"];

    public function genre()
    {
        return $this->belongsTo(Genre::class);
    }

    public function reviews()
    {
        return $this->hasMany(Review::class, 'film_id');
    }

}

app/Http/Controllers/FilmController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Film;
use App\Models\Genre;
use App\Models\Review;

class FilmController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $film = Film::all();
        return view('film.index', compact('film'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $genre = Genre::all();
        return view('film.create',compact('genre'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'judul' => 'required',
            'ringkasan' => 'required',
            'tahun' => 'required',
            'poster' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'genre_id' => 'required'
        ]);

        $fileName = time() . '.' . $request->poster->extension();
        $request->poster->move(public_path('storage/film'), $fileName);
        
        $film = new Film;
        $film->judul = $request->input('judul');
        $film->ringkasan = $request->input('ringkasan');
        $film->tahun = $request->input('tahun');
        $film->poster = $fileName;
        $film->genre_id = $request->input('genre_id');
        $film->save();

        return redirect('/film');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $film = Film::find($id);
        return view('film.show', compact('film'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $film = Film::find($id);
        $genre = Genre::all();
        return view('film.edit', compact('film','genre'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Film $film)
    {
        $fileName = '';

        if ($request->hasFile('poster')) {
          $fileName = time() . '.' . $request->poster->extension();
          $request->poster->move(public_path('storage/film'), $fileName);
          if ($film->poster) {
            unlink('storage/film/'.$film->poster);
          }
        } else {
          $fileName = $film->poster;
        }

        $film->judul = $request->input('judul');
        $film->ringkasan = $request->input('ringkasan');
        $film->tahun = $request->input('tahun');
        $film->poster = $fileName;
        $film->genre_id = $request->input('genre_id');
        $film->save();

        return redirect()->route('film.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Film $film)
    {
        if($film->poster){
            unlink('storage/film/'.$film->poster);
        }
        $film->delete();

        return redirect()->route('film.index')->with([
            'message' => 'film deleted successfully!', 
            'status' => 'success'
        ]);
    }

    public function tampil()
    {
        $film = Film::all();
        return view('film.tampil', compact('film'));
    }

    public function review($id)
    {
        $film = Film::find($id);
        return view('film.review', compact('film'));
    }
}

resources/views/film/create.blade.php
@extends('layouts.master')

@section('sitetitle','MyMovieApp')

@section('title')
Create Film
@endsection

@section('user')
    @auth
    {{ ucwords(auth()->user()->name) }}
    @endauth

    @guest
    Guest
    @endguest
@endsection

@section('user-foto')
    @auth
        @if(auth()->user()->photo)
            <img src="{{asset('storage/user/'. auth()->user()->photo)}}" class="img-circle elevation-2" alt="User Image">
        @else 
            <img src="{{asset('img/user-placeholder.png')}}" class="img-circle elevation-2" alt="User Image">
        @endif
    
    @endauth

    @guest
        <img src="{{asset('img/user-placeholder.png')}}" class="img-circle elevation-2" alt="User Image">
    @endguest

@endsection

@push('scripts')
<script>
    $(function () {
        $("#example1").DataTable();
    });
</script>
<script src="{{asset('AdminLTE-3.2.0/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('AdminLTE-3.2.0/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
@endpush

@push('styles')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.3/datatables.min.css"/>
@endpush

@section('content')

<form action="/film" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="form-group">

        <label for="judul">Judul </label>
        <input type="text" class="form-control" name="judul" id="judul">
        @error('judul')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror

        <label for="ringkasan">Ringkasan</label><br>
        <textarea class="form-control" name="ringkasan" id="ringkasan" cols="30" rows="5"></textarea><br><br>
        @error('ringkasan')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror

        <label for="tahun">Tahun </label>
        <input type="number" id="tahun" class="form-control" name="tahun"><br>
        @error('tahun')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror

        <label class="col-sm-3 col-form-label">Poster</label>
        <div class="col-sm-9">
            <input type="file" class="form-control" name="poster" @error('poster') is-invalid @enderror>
        </div>
        @error('poster')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror

        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <label class="input-group-text" for="inputGroupSelect01">Genre</label>
            </div>
            <select id="genre_id" name="genre_id" class="custom-select" id="inputGroupSelect01">
              <option selected>Choose...</option>
                @forelse ($genre as $key=>$value)
                    <option value="{{ $value->id }}">{{ $value->nama }}</option>
                @empty
                    <option value="">No Genre List</option>
                @endforelse
            </select>
          </div>
        @error('poster')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror

    </div>

    <button type="submit" class="btn btn-primary">Tambah</button>
</form>

@endsection

resources/views/film/edit.blade.php
@extends('layouts.master')

@section('sitetitle','MyMovieApp')

@section('title')
Edit Film
@endsection

@section('user')
    @auth
    {{ ucwords(auth()->user()->name) }}
    @endauth

    @guest
    Guest
    @endguest
@endsection

@section('user-foto')
    @auth
        @if(auth()->user()->photo)
            <img src="{{asset('storage/user/'. auth()->user()->photo)}}" class="img-circle elevation-2" alt="User Image">
        @else 
            <img src="{{asset('img/user-placeholder.png')}}" class="img-circle elevation-2" alt="User Image">
        @endif
    
    @endauth

    @guest
        <img src="{{asset('img/user-placeholder.png')}}" class="img-circle elevation-2" alt="User Image">
    @endguest

@endsection

@push('scripts')
<script>
    $(function () {
        $("#example1").DataTable();
    });
</script>
<script src="{{asset('AdminLTE-3.2.0/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('AdminLTE-3.2.0/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
@endpush

@push('styles')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.3/datatables.min.css"/>
@endpush

@section('content')
<form action="/film/{{$film->id}}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="form-group">

        <label for="judul">Judul </label>
        <input type="text" class="form-control" name="judul" id="judul" value="{{$film->judul}}"><br>
        @error('judul')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror

        <label for="ringkasan">Ringkasan</label>
        <textarea class="form-control" name="ringkasan" id="ringkasan" cols="30" rows="5">{{$film->ringkasan}}</textarea><br>
        @error('ringkasan')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror

        <label for="tahun">Tahun </label>
        <input type="number" id="tahun" class="form-control" name="tahun" value="{{$film->tahun}}"><br>
        @error('tahun')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror

        <label  for="poster">Poster</label>
        <input type="file" class="form-control" name="poster"><br>
        @error('poster')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror

        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <label class="input-group-text" for="inputGroupSelect01">Genre</label>
            </div>
            <select id="genre_id" name="genre_id" class="custom-select" id="inputGroupSelect01">
                <option value={{$film->genre_id}} selected>{{$film->genre->nama}}</option>
                @forelse ($genre as $key=>$value)
                    <option value="{{ $value->id }}">{{ $value->nama }}</option>
                @empty
                    <option value="">No Genre List</option>
                @endforelse
            </select>
          </div>
        @error('poster')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror

    </div>

    <button type="submit" class="btn btn-primary">Tambah</button>
</form>
@endsection

resources/views/film/index.blade.php
@extends('layouts.master')

@section('sitetitle','MyMovieApp')

@section('title')
Film
@endsection

@section('user')
    @auth
    {{ ucwords(auth()->user()->name) }}
    @endauth

    @guest
    Guest
    @endguest
@endsection

@section('user-foto')
    @auth
        @if(auth()->user()->photo)
            <img src="{{asset('storage/user/'. auth()->user()->photo)}}" class="img-circle elevation-2" alt="User Image">
        @else 
            <img src="{{asset('img/user-placeholder.png')}}" class="img-circle elevation-2" alt="User Image">
        @endif
    
    @endauth

    @guest
        <img src="{{asset('img/user-placeholder.png')}}" class="img-circle elevation-2" alt="User Image">
    @endguest

@endsection

@push('scripts')
<script>
    $(function () {
        $("#example1").DataTable();
    });
</script>
<script src="{{asset('AdminLTE-3.2.0/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('AdminLTE-3.2.0/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
@endpush

@push('styles')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.3/datatables.min.css"/>
@endpush

@section('content')
<a href="{{ route('film.create') }}" class="btn btn-primary mb-3">+Tambah</a>
<table id="example1" class="table">
    <thead class="thead-light">
        <tr>
        <th scope="col">#</th>
        <th scope="col">judul</th>
        <th scope="col">ringkasan</th>
        <th scope="col">tahun</th>
        <th scope="col">poster</th>
        <th scope="col">genre</th>
        <th scope="col">aksi</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($film as $key=>$value)
            <tr>
                <td>{{$key + 1}}</th>
                <td>{{$value->judul}}</td>
                <td>{{$value->ringkasan}}</td>
                <td>{{$value->tahun}}</td>
                <td><img src="{{asset('storage/film/'. $value->poster)}}" style="max-width:100%;height: 100px;" class="img-fluid" alt="{{$value->poster}}"></td>
                <td>{{$value->genre->nama}}</td>
                <td>
                <a href="{{ route('film.edit',$value->id) }}" class="btn btn-success btn-xs py-0">Edit</a>
                <a href="{{ route('film.show',$value->id) }}" class="btn btn-secondary btn-xs py-0">Detail</a>
                <form action="/film/{{$value->id}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <input type="submit" class="btn btn-danger btn-xs py-0" value="Delete">
                </form>
                    
                </td>
            </tr>
        @empty
            <tr colspan=7>
                <td>No data</td>
            </tr>  
        @endforelse              
    </tbody>
</table>
@endsection

resources/views/film/review.blade.php
@extends('layouts.master')

@section('sitetitle','MyMovieApp')

@section('title')
Film
@endsection

@section('user')
    @auth
    {{ ucwords(auth()->user()->name) }}
    @endauth

    @guest
    Guest
    @endguest
@endsection

@section('user-foto')
    @auth
        @if(auth()->user()->photo)
            <img src="{{asset('storage/user/'. auth()->user()->photo)}}" class="img-circle elevation-2" alt="User Image">
        @else 
            <img src="{{asset('img/user-placeholder.png')}}" class="img-circle elevation-2" alt="User Image">
        @endif
    
    @endauth

    @guest
        <img src="{{asset('img/user-placeholder.png')}}" class="img-circle elevation-2" alt="User Image">
    @endguest

@endsection

@push('scripts')
<script>
    $(function () {
        $("#example1").DataTable();
    });
</script>
<script src="{{asset('AdminLTE-3.2.0/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('AdminLTE-3.2.0/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
@endpush

@push('styles')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.3/datatables.min.css"/>
<style>
    .card-img-top {
    width: 100%;
    height: 25vw;
    object-fit: cover;
}
</style>
@endpush

@section('content')
<div class="card-deck">
    <div class="card">
        <img class="card-img-top" src="{{asset('storage/film/'. $film->poster)}}" alt="{{$film->judul}}">
        <div class="card-body">
            <h5 class="card-title">{{$film->judul}}</h5>
            <p class="card-text">{{$film->ringkasan}}</p>
            <p class="card-text">{{$film->genre->nama}}</p>
        </div>
    </div>     
</div>


<div class="card">
    <div class="card-body">
        <h4>Display Review</h4><hr />
        @forelse ($film->reviews as $review)
            <img src="{{asset('storage/user/'. $review->users->photo)}}" style="height: 30px;width:30px;" class="img-circle elevation-2" alt="User Image">
            <strong>{{ $review->users->name }}</strong>
            <p>{{ $review->content }}</p>
            <hr />
        @empty
            Tidak ada review
        @endforelse
            
        @auth
        <h4>Add Review</h4>
            <form method="post" action="{{ route('review.store') }}">
                @csrf
                <div class="form-group">
                    <textarea class="form-control" name="content"></textarea>
                    <input type="hidden" name="user_id" value="{{ auth()->user()->id }}" />
                    <input type="hidden" name="film_id" value="{{ $film->id }}" />
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Add Review" />
                </div>
            </form>
            @endauth

            @guest
                Login untuk membuat review
            @endguest
        
    </div>
</div>

@endsection

resources/views/film/show.blade.php
@extends('layouts.master')

@section('sitetitle','MyMovieApp')

@section('title')
Film Detail
@endsection

@section('user')
    @auth
    {{ ucwords(auth()->user()->name) }}
    @endauth

    @guest
    Guest
    @endguest
@endsection

@section('user-foto')
    @auth
        @if(auth()->user()->photo)
            <img src="{{asset('storage/user/'. auth()->user()->photo)}}" class="img-circle elevation-2" alt="User Image">
        @else 
            <img src="{{asset('img/user-placeholder.png')}}" class="img-circle elevation-2" alt="User Image">
        @endif
    
    @endauth

    @guest
        <img src="{{asset('img/user-placeholder.png')}}" class="img-circle elevation-2" alt="User Image">
    @endguest

@endsection

@push('scripts')
<script>
    $(function () {
        $("#example1").DataTable();
    });
</script>
<script src="{{asset('AdminLTE-3.2.0/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('AdminLTE-3.2.0/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
@endpush

@push('styles')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.3/datatables.min.css"/>
@endpush

@section('content')


<div class="card" style="width: 25rem;">
    <img src="{{asset('storage/film/'. $film->poster)}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{$film->judul}}</h5>
      <p class="card-text">{{$film->ringkasan}}</p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Tahun : {{ $film->tahun}}</li>
      <li class="list-group-item">Genre : {{ $film->genre->nama}}</li>
    </ul>
  </div>

    {{-- @forelse ($film->review as $key=>$value)
    <div class="media">
    <img src="{{asset('img/user-placeholder.png')}}" style="max-width:100%;height: 50px;" class="img-fluid img-circle elevation-2" alt="...">
    <div class="media-body">
      <h5 class="mt-0">{{$value->users->nama}}</h5>
      <p>{{$value->content}}</p>
    </div>
    @empty
    <tr colspan=6>
        <td>Belum ada data review</td>
    </tr>  
    @endforelse  
  
  </div> --}}

@endsection

resources/views/film/tampil.blade.php
@extends('layouts.master')

@section('sitetitle','MyMovieApp')

@section('title')
Film
@endsection

@section('user')
    @auth
    {{ ucwords(auth()->user()->name) }}
    @endauth

    @guest
    Guest
    @endguest
@endsection

@section('user-foto')
    @auth
        @if(auth()->user()->photo)
            <img src="{{asset('storage/user/'. auth()->user()->photo)}}" class="img-circle elevation-2" alt="User Image">
        @else 
            <img src="{{asset('img/user-placeholder.png')}}" class="img-circle elevation-2" alt="User Image">
        @endif
    
    @endauth

    @guest
        <img src="{{asset('img/user-placeholder.png')}}" class="img-circle elevation-2" alt="User Image">
    @endguest

@endsection

@push('scripts')
<script>
    $(function () {
        $("#example1").DataTable();
    });
</script>
<script src="{{asset('AdminLTE-3.2.0/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('AdminLTE-3.2.0/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
@endpush

@push('styles')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.3/datatables.min.css"/>
<style>
    .card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
    }
</style>
@endpush

@section('content')

<div class="card-deck">
    @forelse ($film as $key=>$value)
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{{asset('storage/film/'. $value->poster)}}" alt="{{$value->judul}}">
        <div class="card-body h-100">
          <h5 class="card-title">{{$value->judul}}</h5>
          <p class="card-text">{{$value->ringkasan}}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Tahun {{$value->tahun}}</li>
          <li class="list-group-item">Genre {{$value->genre->nama}}</li>
        </ul>
        <div class="card-body">
          <a href="/film/{{$value->id}}/review" class="card-link">Detail</a>
        </div>
      </div>
    @empty
    Tidak ada data film
    @endforelse
</div>



@endsection